[package]
authors = ["The Cloud Hypervisor Authors"]
edition = "2021"
name = "vm-device"
version = "0.1.0"

[features]
default = []
kvm = ["vfio-ioctls/kvm"]
mshv = ["vfio-ioctls/mshv"]

[dependencies]
anyhow = "1.0.87"
serde = { version = "1.0.208", features = ["derive", "rc"] }
thiserror = "1.0.62"
vfio-ioctls = {  git = "https://github.com/Manciukic/vfio", commit = "38e4822" }
vm-memory = { version = "0.16.1", features = ["backend-mmap"] }
vmm-sys-util = ">=0.3.1"
